title: HueCodes
description: Hugh's personal site. Math, ML, robotics, networking, and security. Building devtools, cloud security, and inference engines.
url: "https://huecodes.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

permalink: /blog/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  projects:
    output: true
    permalink: /projects/:name/
  hardware:
    output: true
    permalink: /hardware/:name/
